// Translations for invoice PDF

export const translations = {
  cs: {
    // Document types
    invoice: 'Faktura',
    proforma: 'Proforma faktura',
    creditNote: 'Dobropis',

    // Headers
    seller: 'Dodavatel',
    buyer: 'Odběratel',
    invoiceNumber: 'Číslo faktury',
    issueDate: 'Datum vystavení',
    dueDate: 'Datum splatnosti',
    taxDate: 'Datum zdanitelného plnění',

    // Company info
    taxId: 'IČO',
    vatId: 'DIČ',
    notVatPayer: 'Neplátce DPH',

    // Items table
    description: 'Popis',
    quantity: 'Množství',
    unit: 'MJ',
    unitPrice: 'Cena za MJ',
    taxRate: 'DPH',
    total: 'Celkem',

    // Totals
    subtotal: 'Základ',
    taxAmount: 'DPH',
    totalAmount: 'Celkem k úhradě',

    // Payment
    paymentDetails: 'Platební údaje',
    bankAccount: 'Bankovní účet',
    bankName: 'Banka',
    iban: 'IBAN',
    swift: 'SWIFT',
    variableSymbol: 'Variabilní symbol',
    paymentMethod: 'Forma úhrady',
    bankTransfer: 'Bankovním převodem',

    // Footer
    notes: 'Poznámky',
    generatedBy: 'Vygenerováno v SME Financial OS',

    // Units
    pcs: 'ks',
    hours: 'hod',
  },
  pl: {
    // Document types
    invoice: 'Faktura',
    proforma: 'Faktura proforma',
    creditNote: 'Faktura korygująca',

    // Headers
    seller: 'Sprzedawca',
    buyer: 'Nabywca',
    invoiceNumber: 'Numer faktury',
    issueDate: 'Data wystawienia',
    dueDate: 'Termin płatności',
    taxDate: 'Data sprzedaży',

    // Company info
    taxId: 'NIP',
    vatId: 'NIP UE',
    notVatPayer: 'Podmiot zwolniony z VAT',

    // Items table
    description: 'Opis',
    quantity: 'Ilość',
    unit: 'J.m.',
    unitPrice: 'Cena jedn.',
    taxRate: 'VAT',
    total: 'Razem',

    // Totals
    subtotal: 'Wartość netto',
    taxAmount: 'VAT',
    totalAmount: 'Do zapłaty',

    // Payment
    paymentDetails: 'Dane do przelewu',
    bankAccount: 'Numer konta',
    bankName: 'Bank',
    iban: 'IBAN',
    swift: 'SWIFT',
    variableSymbol: 'Tytuł przelewu',
    paymentMethod: 'Forma płatności',
    bankTransfer: 'Przelew',

    // Footer
    notes: 'Uwagi',
    generatedBy: 'Wygenerowano w SME Financial OS',

    // KSeF
    ksefNumber: 'Numer KSeF',

    // Units
    pcs: 'szt.',
    hours: 'godz.',
  },
  en: {
    // Document types
    invoice: 'Invoice',
    proforma: 'Proforma Invoice',
    creditNote: 'Credit Note',

    // Headers
    seller: 'Seller',
    buyer: 'Buyer',
    invoiceNumber: 'Invoice Number',
    issueDate: 'Issue Date',
    dueDate: 'Due Date',
    taxDate: 'Tax Date',

    // Company info
    taxId: 'Tax ID',
    vatId: 'VAT ID',
    notVatPayer: 'Not VAT registered',

    // Items table
    description: 'Description',
    quantity: 'Qty',
    unit: 'Unit',
    unitPrice: 'Unit Price',
    taxRate: 'VAT',
    total: 'Total',

    // Totals
    subtotal: 'Subtotal',
    taxAmount: 'VAT',
    totalAmount: 'Total Due',

    // Payment
    paymentDetails: 'Payment Details',
    bankAccount: 'Bank Account',
    bankName: 'Bank',
    iban: 'IBAN',
    swift: 'SWIFT',
    variableSymbol: 'Reference',
    paymentMethod: 'Payment Method',
    bankTransfer: 'Bank Transfer',

    // Footer
    notes: 'Notes',
    generatedBy: 'Generated by SME Financial OS',

    // Units
    pcs: 'pcs',
    hours: 'hrs',
  },
} as const;

export type TranslationKey = keyof typeof translations.cs;
export type Locale = keyof typeof translations;

export function t(key: TranslationKey, locale: Locale = 'cs'): string {
  return translations[locale][key] || translations.en[key] || key;
}
