import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Section,
  Text,
  Row,
  Column,
} from '@react-email/components';
import * as React from 'react';

interface InvoiceEmailProps {
  invoiceNumber: string;
  companyName: string;
  customerName: string;
  amount: string;
  currency: string;
  dueDate: string;
  issueDate: string;
  viewLink?: string;
  locale?: 'cs' | 'pl' | 'en';
}

const translations = {
  cs: {
    subject: 'Faktura',
    preview: 'Nová faktura od',
    greeting: 'Dobrý den',
    intro: 'zasíláme Vám fakturu',
    invoiceDetails: 'Detaily faktury',
    invoiceNumber: 'Číslo faktury',
    issueDate: 'Datum vystavení',
    dueDate: 'Datum splatnosti',
    amount: 'Částka k úhradě',
    viewInvoice: 'Zobrazit fakturu',
    attachmentNote: 'Faktura je přiložena k tomuto e-mailu ve formátu PDF.',
    paymentNote: 'Prosíme o úhradu do data splatnosti.',
    thanks: 'Děkujeme za Vaši spolupráci.',
    regards: 'S pozdravem',
    footer: 'Tento e-mail byl automaticky vygenerován systémem SME Financial OS.',
  },
  pl: {
    subject: 'Faktura',
    preview: 'Nowa faktura od',
    greeting: 'Dzień dobry',
    intro: 'przesyłamy fakturę',
    invoiceDetails: 'Szczegóły faktury',
    invoiceNumber: 'Numer faktury',
    issueDate: 'Data wystawienia',
    dueDate: 'Termin płatności',
    amount: 'Kwota do zapłaty',
    viewInvoice: 'Zobacz fakturę',
    attachmentNote: 'Faktura jest załączona do tego e-maila w formacie PDF.',
    paymentNote: 'Prosimy o dokonanie płatności do terminu.',
    thanks: 'Dziękujemy za współpracę.',
    regards: 'Z poważaniem',
    footer: 'Ta wiadomość została automatycznie wygenerowana przez system SME Financial OS.',
  },
  en: {
    subject: 'Invoice',
    preview: 'New invoice from',
    greeting: 'Hello',
    intro: 'please find attached invoice',
    invoiceDetails: 'Invoice Details',
    invoiceNumber: 'Invoice Number',
    issueDate: 'Issue Date',
    dueDate: 'Due Date',
    amount: 'Amount Due',
    viewInvoice: 'View Invoice',
    attachmentNote: 'The invoice is attached to this email as a PDF.',
    paymentNote: 'Please make payment by the due date.',
    thanks: 'Thank you for your business.',
    regards: 'Best regards',
    footer: 'This email was automatically generated by SME Financial OS.',
  },
};

export function InvoiceEmail({
  invoiceNumber,
  companyName,
  customerName,
  amount,
  currency,
  dueDate,
  issueDate,
  viewLink,
  locale = 'en',
}: InvoiceEmailProps) {
  const t = translations[locale];

  return (
    <Html>
      <Head />
      <Preview>{`${t.preview} ${companyName} - ${invoiceNumber}`}</Preview>
      <Body style={main}>
        <Container style={container}>
          {/* Header */}
          <Section style={header}>
            <Heading style={h1}>{companyName}</Heading>
          </Section>

          {/* Greeting */}
          <Section style={section}>
            <Text style={text}>
              {t.greeting} {customerName},
            </Text>
            <Text style={text}>
              {t.intro} <strong>{invoiceNumber}</strong>.
            </Text>
          </Section>

          {/* Invoice Details Box */}
          <Section style={detailsBox}>
            <Heading as="h2" style={h2}>
              {t.invoiceDetails}
            </Heading>
            <Hr style={hr} />
            <Row>
              <Column style={detailLabel}>{t.invoiceNumber}:</Column>
              <Column style={detailValue}>{invoiceNumber}</Column>
            </Row>
            <Row>
              <Column style={detailLabel}>{t.issueDate}:</Column>
              <Column style={detailValue}>{issueDate}</Column>
            </Row>
            <Row>
              <Column style={detailLabel}>{t.dueDate}:</Column>
              <Column style={detailValue}>{dueDate}</Column>
            </Row>
            <Hr style={hr} />
            <Row>
              <Column style={detailLabel}>
                <strong>{t.amount}:</strong>
              </Column>
              <Column style={amountValue}>
                {amount} {currency}
              </Column>
            </Row>
          </Section>

          {/* CTA Button */}
          {viewLink && (
            <Section style={buttonSection}>
              <Link href={viewLink} style={button}>
                {t.viewInvoice}
              </Link>
            </Section>
          )}

          {/* Notes */}
          <Section style={section}>
            <Text style={noteText}>{t.attachmentNote}</Text>
            <Text style={noteText}>{t.paymentNote}</Text>
          </Section>

          {/* Closing */}
          <Section style={section}>
            <Text style={text}>{t.thanks}</Text>
            <Text style={text}>
              {t.regards},
              <br />
              <strong>{companyName}</strong>
            </Text>
          </Section>

          {/* Footer */}
          <Hr style={hr} />
          <Section style={footer}>
            <Text style={footerText}>{t.footer}</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

// Styles
const main = {
  backgroundColor: '#f6f9fc',
  fontFamily:
    '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Ubuntu, sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
  maxWidth: '600px',
};

const header = {
  padding: '32px 48px',
  backgroundColor: '#1a1a1a',
};

const h1 = {
  color: '#ffffff',
  fontSize: '24px',
  fontWeight: '600',
  lineHeight: '1.3',
  margin: '0',
};

const h2 = {
  color: '#1a1a1a',
  fontSize: '18px',
  fontWeight: '600',
  lineHeight: '1.3',
  margin: '0 0 16px',
};

const section = {
  padding: '24px 48px',
};

const text = {
  color: '#525f7f',
  fontSize: '16px',
  lineHeight: '24px',
  margin: '0 0 12px',
};

const noteText = {
  color: '#8898aa',
  fontSize: '14px',
  lineHeight: '20px',
  margin: '0 0 8px',
};

const detailsBox = {
  backgroundColor: '#f8fafc',
  borderRadius: '8px',
  padding: '24px',
  margin: '0 48px 24px',
};

const detailLabel = {
  color: '#8898aa',
  fontSize: '14px',
  padding: '8px 0',
  width: '40%',
};

const detailValue = {
  color: '#1a1a1a',
  fontSize: '14px',
  fontWeight: '500',
  padding: '8px 0',
  textAlign: 'right' as const,
  width: '60%',
};

const amountValue = {
  color: '#1a1a1a',
  fontSize: '20px',
  fontWeight: '700',
  padding: '8px 0',
  textAlign: 'right' as const,
  width: '60%',
};

const hr = {
  borderColor: '#e6ebf1',
  margin: '16px 0',
};

const buttonSection = {
  padding: '0 48px 24px',
  textAlign: 'center' as const,
};

const button = {
  backgroundColor: '#1a1a1a',
  borderRadius: '6px',
  color: '#ffffff',
  fontSize: '16px',
  fontWeight: '600',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '12px 32px',
};

const footer = {
  padding: '24px 48px',
};

const footerText = {
  color: '#8898aa',
  fontSize: '12px',
  lineHeight: '16px',
  textAlign: 'center' as const,
  margin: '0',
};

export default InvoiceEmail;
