import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Section,
  Text,
  Row,
  Column,
} from '@react-email/components';
import * as React from 'react';

interface PaymentReminderProps {
  invoiceNumber: string;
  companyName: string;
  customerName: string;
  amount: string;
  currency: string;
  dueDate: string;
  daysOverdue?: number;
  viewLink?: string;
  locale?: 'cs' | 'pl' | 'en';
}

const translations = {
  cs: {
    subject: 'Připomínka platby',
    subjectOverdue: 'Upomínka - faktura po splatnosti',
    preview: 'Připomínka platby faktury',
    greeting: 'Dobrý den',
    reminderIntro: 'dovolujeme si Vám připomenout nezaplacenou fakturu',
    overdueIntro: 'dovolujeme si Vás upozornit, že faktura je po splatnosti',
    daysOverdue: 'dní po splatnosti',
    invoiceDetails: 'Detaily faktury',
    invoiceNumber: 'Číslo faktury',
    dueDate: 'Datum splatnosti',
    amount: 'Částka k úhradě',
    viewInvoice: 'Zobrazit fakturu',
    paymentRequest: 'Prosíme o neprodlenou úhradu.',
    ifPaid: 'Pokud jste již platbu provedli, považujte tento e-mail za bezpředmětný.',
    thanks: 'Děkujeme za pochopení.',
    regards: 'S pozdravem',
    footer: 'Tento e-mail byl automaticky vygenerován systémem SME Financial OS.',
  },
  pl: {
    subject: 'Przypomnienie o płatności',
    subjectOverdue: 'Upomnienie - faktura po terminie',
    preview: 'Przypomnienie o płatności faktury',
    greeting: 'Dzień dobry',
    reminderIntro: 'przypominamy o niezapłaconej fakturze',
    overdueIntro: 'informujemy, że termin płatności faktury minął',
    daysOverdue: 'dni po terminie',
    invoiceDetails: 'Szczegóły faktury',
    invoiceNumber: 'Numer faktury',
    dueDate: 'Termin płatności',
    amount: 'Kwota do zapłaty',
    viewInvoice: 'Zobacz fakturę',
    paymentRequest: 'Prosimy o niezwłoczne uregulowanie płatności.',
    ifPaid: 'Jeśli płatność została już dokonana, prosimy zignorować tę wiadomość.',
    thanks: 'Dziękujemy za zrozumienie.',
    regards: 'Z poważaniem',
    footer: 'Ta wiadomość została automatycznie wygenerowana przez system SME Financial OS.',
  },
  en: {
    subject: 'Payment Reminder',
    subjectOverdue: 'Overdue Notice',
    preview: 'Payment reminder for invoice',
    greeting: 'Hello',
    reminderIntro: 'this is a friendly reminder about the unpaid invoice',
    overdueIntro: 'we would like to inform you that the following invoice is overdue',
    daysOverdue: 'days overdue',
    invoiceDetails: 'Invoice Details',
    invoiceNumber: 'Invoice Number',
    dueDate: 'Due Date',
    amount: 'Amount Due',
    viewInvoice: 'View Invoice',
    paymentRequest: 'Please make payment at your earliest convenience.',
    ifPaid: 'If you have already made payment, please disregard this email.',
    thanks: 'Thank you for your understanding.',
    regards: 'Best regards',
    footer: 'This email was automatically generated by SME Financial OS.',
  },
};

export function PaymentReminderEmail({
  invoiceNumber,
  companyName,
  customerName,
  amount,
  currency,
  dueDate,
  daysOverdue,
  viewLink,
  locale = 'en',
}: PaymentReminderProps) {
  const t = translations[locale];
  const isOverdue = daysOverdue && daysOverdue > 0;

  return (
    <Html>
      <Head />
      <Preview>{`${t.preview} ${invoiceNumber}`}</Preview>
      <Body style={main}>
        <Container style={container}>
          {/* Header */}
          <Section style={isOverdue ? headerOverdue : header}>
            <Heading style={h1}>{companyName}</Heading>
          </Section>

          {/* Overdue Badge */}
          {isOverdue && (
            <Section style={overdueSection}>
              <Text style={overdueBadge}>
                {daysOverdue} {t.daysOverdue}
              </Text>
            </Section>
          )}

          {/* Greeting */}
          <Section style={section}>
            <Text style={text}>
              {t.greeting} {customerName},
            </Text>
            <Text style={text}>
              {isOverdue ? t.overdueIntro : t.reminderIntro}{' '}
              <strong>{invoiceNumber}</strong>.
            </Text>
          </Section>

          {/* Invoice Details Box */}
          <Section style={isOverdue ? detailsBoxOverdue : detailsBox}>
            <Heading as="h2" style={h2}>
              {t.invoiceDetails}
            </Heading>
            <Hr style={hr} />
            <Row>
              <Column style={detailLabel}>{t.invoiceNumber}:</Column>
              <Column style={detailValue}>{invoiceNumber}</Column>
            </Row>
            <Row>
              <Column style={detailLabel}>{t.dueDate}:</Column>
              <Column style={isOverdue ? detailValueOverdue : detailValue}>
                {dueDate}
              </Column>
            </Row>
            <Hr style={hr} />
            <Row>
              <Column style={detailLabel}>
                <strong>{t.amount}:</strong>
              </Column>
              <Column style={amountValue}>
                {amount} {currency}
              </Column>
            </Row>
          </Section>

          {/* CTA Button */}
          {viewLink && (
            <Section style={buttonSection}>
              <Link href={viewLink} style={isOverdue ? buttonOverdue : button}>
                {t.viewInvoice}
              </Link>
            </Section>
          )}

          {/* Notes */}
          <Section style={section}>
            <Text style={text}>{t.paymentRequest}</Text>
            <Text style={noteText}>{t.ifPaid}</Text>
          </Section>

          {/* Closing */}
          <Section style={section}>
            <Text style={text}>{t.thanks}</Text>
            <Text style={text}>
              {t.regards},
              <br />
              <strong>{companyName}</strong>
            </Text>
          </Section>

          {/* Footer */}
          <Hr style={hr} />
          <Section style={footer}>
            <Text style={footerText}>{t.footer}</Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

// Styles
const main = {
  backgroundColor: '#f6f9fc',
  fontFamily:
    '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Ubuntu, sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
  maxWidth: '600px',
};

const header = {
  padding: '32px 48px',
  backgroundColor: '#1a1a1a',
};

const headerOverdue = {
  padding: '32px 48px',
  backgroundColor: '#dc2626',
};

const h1 = {
  color: '#ffffff',
  fontSize: '24px',
  fontWeight: '600',
  lineHeight: '1.3',
  margin: '0',
};

const h2 = {
  color: '#1a1a1a',
  fontSize: '18px',
  fontWeight: '600',
  lineHeight: '1.3',
  margin: '0 0 16px',
};

const section = {
  padding: '24px 48px',
};

const overdueSection = {
  padding: '16px 48px',
  textAlign: 'center' as const,
};

const overdueBadge = {
  backgroundColor: '#fef2f2',
  borderRadius: '999px',
  color: '#dc2626',
  display: 'inline-block',
  fontSize: '14px',
  fontWeight: '600',
  padding: '8px 16px',
  margin: '0',
};

const text = {
  color: '#525f7f',
  fontSize: '16px',
  lineHeight: '24px',
  margin: '0 0 12px',
};

const noteText = {
  color: '#8898aa',
  fontSize: '14px',
  lineHeight: '20px',
  margin: '0 0 8px',
};

const detailsBox = {
  backgroundColor: '#f8fafc',
  borderRadius: '8px',
  padding: '24px',
  margin: '0 48px 24px',
};

const detailsBoxOverdue = {
  backgroundColor: '#fef2f2',
  borderRadius: '8px',
  border: '1px solid #fecaca',
  padding: '24px',
  margin: '0 48px 24px',
};

const detailLabel = {
  color: '#8898aa',
  fontSize: '14px',
  padding: '8px 0',
  width: '40%',
};

const detailValue = {
  color: '#1a1a1a',
  fontSize: '14px',
  fontWeight: '500',
  padding: '8px 0',
  textAlign: 'right' as const,
  width: '60%',
};

const detailValueOverdue = {
  color: '#dc2626',
  fontSize: '14px',
  fontWeight: '600',
  padding: '8px 0',
  textAlign: 'right' as const,
  width: '60%',
};

const amountValue = {
  color: '#1a1a1a',
  fontSize: '20px',
  fontWeight: '700',
  padding: '8px 0',
  textAlign: 'right' as const,
  width: '60%',
};

const hr = {
  borderColor: '#e6ebf1',
  margin: '16px 0',
};

const buttonSection = {
  padding: '0 48px 24px',
  textAlign: 'center' as const,
};

const button = {
  backgroundColor: '#1a1a1a',
  borderRadius: '6px',
  color: '#ffffff',
  fontSize: '16px',
  fontWeight: '600',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '12px 32px',
};

const buttonOverdue = {
  backgroundColor: '#dc2626',
  borderRadius: '6px',
  color: '#ffffff',
  fontSize: '16px',
  fontWeight: '600',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '12px 32px',
};

const footer = {
  padding: '24px 48px',
};

const footerText = {
  color: '#8898aa',
  fontSize: '12px',
  lineHeight: '16px',
  textAlign: 'center' as const,
  margin: '0',
};

export default PaymentReminderEmail;
